=== Dadda1234561/MMulta/dist/gameserver/data/costumes.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT list (costume)*>

<!ELEMENT costume (need_item | extract_fee)*>
<!ATTLIST costume
        id CDATA #REQUIRED
        visual_item_id CDATA #REQUIRED
        costume_skill CDATA #REQUIRED
        evolution_need CDATA #REQUIRED
        origin_type CDATA #REQUIRED
        grade CDATA #REQUIRED>

<!ELEMENT need_item (item)*>
<!ELEMENT extract_fee (item)*>

<!ELEMENT item (#PCDATA)>
<!ATTLIST item
        id CDATA #REQUIRED
        count CDATA #REQUIRED>

=== Dadda1234561/MMulta/dist/gameserver/data/costumes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE list SYSTEM "costumes.dtd">
<!-- AUTHOR: sharp -->
<list>

    <costume id="1" visual_item_id="80767"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>

    <costume id="2" visual_item_id="80768"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>

    <costume id="3" visual_item_id="96270"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>

    <costume id="4" visual_item_id="97503"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="5" visual_item_id="95847"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="6" visual_item_id="94813"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="7" visual_item_id="94812"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="8" visual_item_id="91746"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="9" visual_item_id="91261"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="10" visual_item_id="49531"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>


    <costume id="11" visual_item_id="26330"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="12" visual_item_id="26328"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="13" visual_item_id="26326"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="14" visual_item_id="26254"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="15" visual_item_id="48766"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="16" visual_item_id="48765"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="17" visual_item_id="24133"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="18" visual_item_id="46601"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="19" visual_item_id="46600"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="20" visual_item_id="46595"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="21" visual_item_id="81397"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="22" visual_item_id="81398"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="23" visual_item_id="81399"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1" >
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="24" visual_item_id="46192"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="25" visual_item_id="23881"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>



    <costume id="26" visual_item_id="23879"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="27" visual_item_id="46262"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="28" visual_item_id="46261"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="29" visual_item_id="46260"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="30" visual_item_id="81044"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="31" visual_item_id="81045"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
    <costume id="32" visual_item_id="23485"  costume_skill="59158;1" evolution_need="10" origin_type="1" grade="1">
        <need_item>
            <item id="4037" count="1000" />
        </need_item>
        <extract_fee>
            <item id="57" count="1000000" />
        </extract_fee>
    </costume>
